const Listings = [
  {
    _id: 1,
    name: "Title 1",
    address: "4-cairo",
    desc: "lorem ipsum dolor sit amet, con lorem ipsum dolor lorem",
    image:
      "https://www.livehome3d.com/assets/img/social/how-to-design-a-house.jpg",
    price: 200,
    beds: 2,
    baths: 1,
    parking: false,
    furnished: true,
    offer: false,
    type: "rent",
  },
  {
    _id: 2,
    name: "Title 2",
    address: "5-cairo",
    desc: "lorem ipsum dolor sit amet, con lorem ipsum dolor loremlorem ipsum dolor sit amet, con lorem ipsum dolor loremlorem ipsum dolor sit amet, con lorem ipsum dolor loremlorem ipsum dolor sit amet, con lorem ipsum dolor loremlorem ipsum dolor sit amet, con lorem ipsum dolor loremlorem ipsum dolor sit amet, con lorem ipsum dolor loremlorem ipsum dolor sit amet, con lorem ipsum dolor loremlorem ipsum dolor sit amet, con lorem ipsum dolor lorem",
    image:
      "https://www.livehome3d.com/assets/img/social/how-to-design-a-house.jpg",
    price: 200,
    beds: 2,
    baths: 1,
    parking: false,
    furnished: true,
    offer: false,
    type: "sell",
  },
  {
    _id: 3,
    name: "Title 3",
    address: "4-cairo",
    desc: "lorem ipsum dolor sit amet, con lorem ipsum dolor lorem",
    image:
      "https://www.livehome3d.com/assets/img/social/how-to-design-a-house.jpg",
    price: 200,
    beds: 2,
    baths: 1,
    parking: true,
    furnished: true,
    offer: true,
    type: "sell & rent",
  },
  {
    _id: 4,
    name: "Title 3",
    address: "4-cairo",
    desc: "lorem ipsum dolor sit amet, con lorem ipsum dolor lorem",
    image:
      "https://www.livehome3d.com/assets/img/social/how-to-design-a-house.jpg",
    price: 200,
    beds: 2,
    baths: 1,
    parking: false,
    furnished: true,
    offer: true,
    type: "sell & rent",
  },
  {
    _id: 5,
    name: "Title 3",
    address: "4-cairo",
    desc: "lorem ipsum dolor sit amet, con lorem ipsum dolor lorem",
    image:
      "https://www.livehome3d.com/assets/img/social/how-to-design-a-house.jpg",
    price: 200,
    beds: 2,
    baths: 1,
    parking: false,
    furnished: true,
    offer: true,
    type: "sell & rent",
  },
  {
    _id: 6,
    name: "Title 3",
    address: "4-cairo",
    desc: "lorem ipsum dolor sit amet, con lorem ipsum dolor lorem",
    image:
      "https://www.livehome3d.com/assets/img/social/how-to-design-a-house.jpg",
    price: 200,
    beds: 2,
    baths: 1,
    parking: false,
    furnished: true,
    offer: true,
    type: "sell & rent",
  },
  {
    _id: 7,
    name: "Title 3",
    address: "4-cairo",
    desc: "lorem ipsum dolor sit amet, con lorem ipsum dolor lorem",
    image:
      "https://www.livehome3d.com/assets/img/social/how-to-design-a-house.jpg",
    price: 200,
    beds: 2,
    baths: 1,
    parking: false,
    furnished: true,
    offer: true,
    type: "sell & rent",
  },
];

export { Listings };
